---

- name: Configure New Relic infra
  become: yes
  template:
    dest: /etc/newrelic-infra.yml
    group: "{{ sansible_newrelic_group }}"
    mode: 0640
    owner: "{{ sansible_newrelic_user }}"
    src: newrelic-infra.yml.j2
  when: sansible_newrelic_integrations_infra_enabled == true
  notify:
    - restart newrelic infra

- name: Start New Relic Infra if start on boot enabled
  become: yes
  service:
    name: newrelic-infra
    state: started
  when:
    - sansible_newrelic_integrations_infra_enabled == true
    - sansible_newrelic_integrations_infra_start_on_boot == true

- name: Configure New Relic PHP integration
  become: yes
  ini_file:
    dest: "{{ sansible_newrelic_integrations_php_ini_paths_base }}"
    mode: 0644
    section: "{{ item.section | default(None) }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  when:
    - sansible_newrelic_integrations_php_enabled == true
    - sansible_newrelic_integrations_php_start_on_boot == true
  with_items: "{{ [
        {
          'option': 'extension',
          'value': 'newrelic.so'
        },
        {
          'option': 'newrelic.license',
          'section': 'newrelic',
          'value': sansible_newrelic_license_key
        },
        {
          'option': 'newrelic.loglevel',
          'section': 'newrelic',
          'value': sansible_newrelic_log_level
        },
        {
          'option': 'newrelic.appname',
          'section': 'newrelic',
          'value': sansible_newrelic_appname_prefix + sansible_newrelic_appname
        },
        {
          'option': 'newrelic.daemon.loglevel',
          'section': 'newrelic',
          'value': sansible_newrelic_log_level
        },
        {
          'option': 'newrelic.process_host.display_name',
          'section': 'newrelic',
          'value': sansible_newrelic_integrations_infra_display_name
        }
      ] + sansible_newrelic_integrations_php_ini_config
    }}"

- name: Configure New Relic PHP integration labels if set
  become: yes
  ini_file:
    dest: "{{ sansible_newrelic_integrations_php_ini_paths_base }}"
    mode: 0644
    section: newrelic
    option: newrelic.labels
    value: "\"{%- set tmp_list = [] -%}
              {%- for attribute_key, attribute_value in sansible_newrelic_labels.iteritems() -%}
                {{ tmp_list.append(attribute_key + ':' + attribute_value) }}
              {%- endfor -%}
            {{ tmp_list |join(';') }}\""
  when:
    - sansible_newrelic_integrations_php_enabled == true
    - sansible_newrelic_integrations_php_start_on_boot == true
    - 'sansible_newrelic_labels | length > 0'

- name: Enable New Relic PHP integration
  become: yes
  file:
    dest: "{{ item }}"
    src: "{{ sansible_newrelic_integrations_php_ini_paths_base }}"
    state: link
  with_items: "{{ sansible_newrelic_integrations_php_ini_paths_links }}"
  when:
    - sansible_newrelic_integrations_php_enabled == true
    - sansible_newrelic_integrations_php_start_on_boot == true
